language: python
python:
    - 3.6
sudo: false

cache: pip
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - "sudo rm -f /etc/boto.cfg"  # See https://github.com/travis-ci/travis-ci/issues/7940
install:
    - pip install -U pip wheel codecov
    - make requirements
script:
    - make validate_translations
    - make validate
    - make pii_check
    - make static
    - make validate_api_committed
after_success:
    - codecov
